#!/bin/bash

set -o errexit
set -o nounset

CELERY_FLOWER_USER="${CELERY_FLOWER_USER:-"admin"}"
CELERY_FLOWER_PASSWORD="${CELERY_FLOWER_PASSWORD:-"flowerdmin"}"

export FLOWER_BASIC_AUTH="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"

celery flower \
    --app=taiga \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
